config/routes.rb
Whatshallwedo::Application.routes.draw do
  resources :activities do
    collection do
      get 'suggestions'
    end
  end
  put 'activities/suggestions/criteria' => 'criteria#update'
  delete 'activities/suggestions/criteria' => 'criteria#destroy'
  root 'activities#suggestions'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :weather

  def self.random_undone(amount_to_return)
    Activity.where(:done => false).random(amount_to_return)
  end
end

app/models/criteria.rb
class Criteria
  attr_reader :weather_id
  def initialize(attrs = nil)
    @weather_id = attrs['weather_id'].to_i unless attrs.nil?
  end
end

app/models/weather.rb
class Weather < ActiveRecord::Base
  has_many :undone_activities, -> { where done: false }, class_name: 'Activity'
  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def suggestions
    criteria_in_session = session[:criteria]
    @all_weathers = Weather.all
    if criteria_in_session.nil?
      @criteria = Criteria.new
      @suggestions = Activity.random_undone(10)
    else
      @criteria = criteria_in_session 
      @suggestions = Weather.find(@criteria.weather_id).undone_activities
    end
  end

  def create
    activity = Activity.create(create_activity_params)
    redirect_to suggestions_activities_path, :notice => "'#{create_activity_params[:name]}' created"
  end

  def update
    activity = Activity.find_by_id(params[:id])
    activity.update_attributes(done_activity_params)
    redirect_to suggestions_activities_path, :notice => "'#{activity.name}' marked as done"
  end

  private

  def create_activity_params
    params.require(:activity).permit(:name, :weather_id)
  end

  def done_activity_params
    params.require(:activity).permit(:done)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/criteria_controller.rb
class CriteriaController < ApplicationController 
  def update
    session[:criteria] = Criteria.new(criteria_params)
    redirect_to suggestions_activities_path
  end

  private
  def criteria_params
    params.require(:criteria).permit(:weather_id)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/suggestions.html.haml
=form_for :criteria, :url => activities_suggestions_criteria_path, 
  :html => {:id => :criteria}, :method => :put do |f|
  =f.label :weather_id
  =f.select :weather_id, 
    options_from_collection_for_select(@all_weathers, 'id', 'name', @criteria.weather_id)
  =f.submit :filter
%table#list_of_suggestions
  %thead
    %tr
      %th Activity
      %th Suitability
  %tbody
    -@suggestions.each do | suggestion |
      %tr
        %td= suggestion.name
        %td= suggestion.weather.name 
        %td
          =form_for suggestion, url: activity_path(suggestion), method: :patch do |f|
            =f.hidden_field :done, :value => true
            =f.submit :Done
=form_for :activity, url: {action: "create"},html: {id: "new_activity_form"}  do |f|
  =f.label :name
  =f.text_field :name
  =f.label :weather_id
  =f.select :weather_id, 
    options_from_collection_for_select(@all_weathers, 'id', 'name', @criteria.weather_id)
  =f.submit :Save

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Whatshallwedo
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        = content_tag :div, msg, :id => "flash_#{name}"
    %body
      = yield